version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    commit-message:
      prefix: 'chore(actions)'
    schedule:
      interval: weekly
      day: monday
      time: '09:00'
      timezone: Asia/Tokyo
  - package-ecosystem: npm
    directory: /
    commit-message:
      prefix: 'chore(deps)'
      prefix-development: 'chore(deps-dev)'
    schedule:
      interval: weekly
      day: monday
      time: '09:00'
      timezone: Asia/Tokyo
